// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddToFavouriteAnimationController from "./add_to_favourite_animation_controller"
application.register("add-to-favourite-animation", AddToFavouriteAnimationController)

import CardsCarouselController from "./cards_carousel_controller"
application.register("cards-carousel", CardsCarouselController)

import DisplayCircleRatingsController from "./display_circle_ratings_controller"
application.register("display-circle-ratings", DisplayCircleRatingsController)
import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)
import InsertInListController from "./insert_in_list_controller"
application.register("insert-in-list", InsertInListController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)
