// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddToFavouriteAnimationController from "./add_to_favourite_animation_controller"
application.register("add-to-favourite-animation", AddToFavouriteAnimationController)

import CardsCarouselController from "./cards_carousel_controller"
application.register("cards-carousel", CardsCarouselController)

import DisplayCircleRatingsController from "./display_circle_ratings_controller"
application.register("display-circle-ratings", DisplayCircleRatingsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)
