development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("redis://default:ehpRQXxcWBGKAlyFX3Yj86OMSsAhCpct@redis-10236.c226.eu-west-1-3.ec2.cloud.redislabs.com:10236") { "redis://localhost:6379/1" } %>
  channel_prefix: rails_uni_review_production
